### ISSUE TITLE
Rendering Screen Crash (XNet 1.7.0+?)

### ISSUE THREAD

**Issue by NillerMedDild** [asiekierka/YNot#7]
Trying to make a gas channel resulted in a hardcrash - Looking in the GUI of the Controller where I made the channel results in another crash.

Crashlog: https://gist.github.com/NillerMedDild/84c673e1e8d0b7ff039150e0a9d97133

YNot-0.2.2
mcjtylib-1.12-3.0.1
xnet-1.12-1.7.1

**Comment by NillerMedDild** [comment]
Thank you :)

**Comment by asiekierka** [comment]
Fixed in YNot 0.2.3+.

**Comment by NillerMedDild** [comment]
I really appreciate the fast fix, thanks!
