### ISSUE TITLE
Channels Resetting on Server Restart

### ISSUE THREAD

**Issue by NillerMedDild** [asiekierka/YNot#8]
I'm not sure this is caused by YNot, but it happened in a recent update. Whenever certain servers reset, XNet Controllers also reset - Their GUIs will be completely blank. When you break and replace the Connector connected to them, some of the channels can show back up. I have very limited information on the issue, as I've been having a hard time replicating it - I was hoping you had a suspicion of what the cause could be, before I dive deeper into testing.

Forge 1.12.2-14.23.4.2708
YNot-0.2.3
xnet-1.12-1.7.1
mcjtylib-1.12-3.0.1

**Comment by asiekierka** [comment]
Nothing in the logs?

**Comment by Xinoe** [comment]
https://clips.twitch.tv/DependableMistyDonkeyBIRB

well a clip from my stream with the problem,, hope it helps.. :)

**Comment by NillerMedDild** [comment]
Here's a log from one of my users, it's happening in his SP world, so I guess it's not just servers.
https://gist.github.com/NillerMedDild/e6fae5250b87b85ea20e00ab973d92e0

**Comment by asiekierka** [comment]
@McJty Any hints as to what could be going wrong?

**Comment by McJty** [comment]
Hmm. The log doesn't say much. At the moment I have no clue. Never seen this happen before

**Comment by NillerMedDild** [comment]
Ah, someone pinned it down, it's not related to YNot at all, it seems:
https://github.com/McJtyMods/XNet/issues/283
