### ISSUE TITLE
Gui Icon Crash on Server

### ISSUE THREAD

**Issue by FallenEagle1** [asiekierka/YNot#9]
Opening up an xnet controller that had a channel for gas gave me the error: java.lang.NoSuchFieldError: iconGuiElements Connected through xnet was cyclic harvester, an infinite water source, and 3 mekanism machines: electrolytic separator, crusher, and a pressurized reaction chamber.

Modpack: All the Mods 3 5.9.7b
Forge: 1.12.2-14.23.4.2707
Xnet: 1.12-1.7.0
Ynot: 0.2.2

Logs: https://paste.ee/p/Ih3jt#s=0&l=10516
It contains more than I intended, so I linked the point of interest (line 10516 is the start of the errors in the log)

**Comment by asiekierka** [comment]
Update to YNot 0.2.3.
